### ISSUE TITLE
Create a transform assign

### ISSUE THREAD

**Issue by felipeddest** [felipeddest/symphony-esb#2]
Transform data in a smart way in purely JS.

What I have in mind is a dynamically JS load from services folder, that will expect a file like this:

`export default function transform (input) {`
`<<SOME LOGIC HERE>>`
`return output`
`}`

This transformation is called when you make an assign and put a 'transformationFile' otherwise 'value' or 'expression'.

**Comment by felipeddest** [comment]
@rafaeljesus what you think of it?

**Comment by felipeddest** [comment]
Implemented on master

**Comment by rafaeljesus** [comment]
:+1:
